### ISSUE TITLE
Missing documentation for SCLOrkWiimote

### ISSUE THREAD

**Issue by grammoboy2** [SCLOrkHub/SCLOrkTools#21]
Missing documentation for SCLOrkWiimote

I'm pretty new to SC, but I know the basics. The SCLOrkWiimote doesn't have any documentation though, so I don't know how to use it.

I'm able to connect the Wiimote on Linux and I can connect it in SC via HID.

**Comment by lnihlen** [comment]
Hey, thanks for checking out the SCLOrkTools Quark. I've started PR #22 to add documentation for the SCLOrkWiimote. I'll merge shortly then release a new version of the Quark including the documentation.

**Comment by grammoboy2** [comment]
Great, thanks.
