### ISSUE TITLE
SCLOrkWiimote.new doesn't seems to work 

### ISSUE THREAD

**Issue by grammoboy2** [SCLOrkHub/SCLOrkTools#23]
SCLOrkWiimote.new doesn't seems to work on version 0.0.14

1 Wiimote connected on Debian testing via blueman-applet 2.1.2 (XWiimote)

Supercollider 3.11 on Debian testing

```
(
SCLOrkWiimote.isConnected;
)
```

HID: found 1 devices
IdentityDictionary[  ]
-> true

```
(
~w = SCLOrkWiimote.new ;
)

```

HID: found 2 devices
IdentityDictionary[ (1 -> a HIDInfo(, Nintendo RVL-CNT-01, IDs:1406, 774, /dev/hidraw1, 00:27:09:26:19:91, 0, -1)) ]
ERROR: Message 'productID' not understood.
RECEIVER:
   nil
ARGS:
PATH: /home/user/supercollider/Wii-hid-1.scd
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand
		arg this = nil
		arg selector = 'productID'
		arg args = [*0]
	Meta_SCLOrkWiimote:new
		arg this = <instance of Meta_SCLOrkWiimote>
		var deviceList = <instance of IdentityDictionary>
		var productId = nil
		var path = nil
		var hid = nil
	< closed FunctionDef >  (no arguments or variables)
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "(
~w = SCLOrkWiimote.new ;
)"
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'productID' not understood.
RECEIVER: nil

`HID.postAvailable;`

HID: found 2 devices
-> IdentityDictionary[ (1 -> a HIDInfo(, Nintendo RVL-CNT-01, IDs:1406, 774, /dev/hidraw1, 00:27:09:26:19:91, 0, -1)), (0 -> a HIDInfo(Burr-Brown from TI              , USB Audio CODEC , IDs:2235, 10498, /dev/hidraw0, , 256, 3)) ]
0: 	Usage name and page: 	undefined, 	undefined
	Vendor name: 	Burr-Brown from TI              
	Product name: 	USB Audio CODEC 
	Vendor and product ID: 	2235, 10498
	Path: 	/dev/hidraw0
	Serial Number: 	
	Releasenumber and interfaceNumber: 	256, 3
1: 	Usage name and page: 	undefined, 	undefined
	Vendor name: 	
	Product name: 	Nintendo RVL-CNT-01
	Vendor and product ID: 	1406, 774
	Path: 	/dev/hidraw1
	Serial Number: 	00:27:09:26:19:91
	Releasenumber and interfaceNumber: 	0, -1
-> HID

`~myhid = HID.open( 1406, 774);`

HID: path was not set specified yet, chosen the one with path: /dev/hidraw1
open device 0x55b3e841da10
start polling thread for -377198064
HID: Opened device: a HIDInfo(, Nintendo RVL-CNT-01, IDs:1406, 774, /dev/hidraw1, 00:27:09:26:19:91, 0, -1)
-> a HID

**Comment by lnihlen** [comment]
Tell me more about the XWiimote thing - is this just your Wiimote paired to your computer? Or is that some special Wiimote emulator or something?

**Comment by grammoboy2** [comment]
XWiimote is an open-source linux device driver for Nintendo Wii / Wii U Remotes and compatible devices. 

The kernel driver is available since linux-3.1 upstream. However, you need at least linux-3.11 for a hotplug-capable driver and proper device support. 

http://dvdhrm.github.io/xwiimote/

**Comment by lnihlen** [comment]
I have a feeling that may be the issue, as it's the only substantive difference between my setup and yours. You'll need to connect your Wiimote via raw HID, pair it like any ordinary bluetooth device.

**Comment by grammoboy2** [comment]
I think xwiimote is the new normal. I've paired it like a normal bluetooth device afaik, using blueman-applet

**Comment by grammoboy2** [comment]
See also: https://github.com/supercollider/supercollider/issues/4843#issuecomment-606374903

**Comment by lnihlen** [comment]
Ah - yeah looks like my linux is loading some wiimote-specific stuff too when I connect:

```
luken@pop-os:~/src/ext/supercollider/build$ lsmod | grep -i wiimote
hid_wiimote            61440  0
ff_memless             20480  1 hid_wiimote
hid                   131072  4 hidp,usbhid,hid_wiimote,hid_generic
```

OK, so the other thing I notice is that my model has a -TR suffix, when I run SCLOrkWiimote.new I get:

```
open device 0x55d23364afe0
HID: Opened device: a HIDInfo(, Nintendo RVL-CNT-01-TR, IDs:1406, 816, /dev/hidraw3, 40:f4:07:0c:ce:b4, 0, -1)
start polling thread for 889042064
```
According to https://wiibrew.org/wiki/Wiimote#SDP_information yours is an older Wiimote. I think I can do a patch to fix this to talk to both.

**Comment by lnihlen** [comment]
But I'll need to ask you to test, since I don't have an older Wiimote.

**Comment by grammoboy2** [comment]
Thats's ok

**Comment by lnihlen** [comment]
Mistakenly closed. Turns out the issue was more likely that I haven't tested on a computer that had something else connected to Bluetooth. I've released 0.0.15, please try to update to that and see if it fixes your issue.

**Comment by grammoboy2** [comment]
Seems to work. Thanks!

**Comment by lnihlen** [comment]
Cool, glad to hear it. Closing this issue.
