### ISSUE TITLE
SCLOrkChat: private messages not working

### ISSUE THREAD

**Issue by brunoruviaro** [SCLOrkHub/SCLOrkTools#32]
When a private message (chat message starting with @user) is sent, it is displayed to all instead of just privately. The header of the message says, "user1 to user2, nil:"

**Comment by lnihlen** [comment]
Looking at the old sclang-based chat server it is clear that private message filtering happened on the server side. The new C++-based server does not do this filtering. It would probably be easier to add the filtering to the client-side code.
