### ISSUE TITLE
Error installing SCLOrkTools

### ISSUE THREAD

**Issue by brunoruviaro** [SCLOrkHub/SCLOrkTools#5]
Just got this error message upon installing SCLOrkTools on a laptop running SC 3.9.0-beta1:

> Open ended string started on line 189 of file '/home/ruviaro/.local/share/SuperCollider/downloaded-quarks/SCLOrkTools/classes/SCLOrkPDPreset.sc'
> ERROR: Superclass 'Menu' of class 'SCLOrkEmojiMenu' is not defined in any file.
> /home/ruviaro/.local/share/SuperCollider/downloaded-quarks/SCLOrkTools/scide_scqt/SCLOrkEmojiMenu.sc
> ERROR: There is a discrepancy.
> numClassDeps 1823   gNumClasses 3644

**Comment by lnihlen** [comment]
I didn't get an email when you filed this issue.. odd. Most likely this is because Menu was added more recently. Can you please try again when you update the laptops to 3.10.x?

**Comment by lnihlen** [comment]
Since we've used SCLOrkTools on the laptops, I'm assuming the upgrade to SC 3.10 fixed this. Closing for now.
